// Demo data used when Supabase is not configured
export const DEMO_ALBUMS = [
  {
    id: 'album-1',
    name: 'Our Moments',
    slug: 'our-moments',
    description: 'Beautiful moments together',
    color: '#ff6b9d',
    cover_url: null,
    sort_order: 1,
    created_at: '2024-02-14T00:00:00Z',
  },
  {
    id: 'album-2',
    name: 'Adventures',
    slug: 'adventures',
    description: 'Exploring the world together',
    color: '#6bcbff',
    cover_url: null,
    sort_order: 2,
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'album-3',
    name: 'Daily Life',
    slug: 'daily-life',
    description: 'Everyday happiness',
    color: '#ffd93d',
    cover_url: null,
    sort_order: 3,
    created_at: '2024-04-01T00:00:00Z',
  },
];

export const DEMO_POSTS = [
  {
    id: 'post-1',
    album_id: 'album-1',
    caption: 'Our first photo together 💕 The start of something beautiful.',
    media_url: '/demo/couple1.jpg',
    media_type: 'image',
    thumbnail_url: null,
    date_taken: '2024-02-14',
    is_featured: true,
    created_at: '2024-02-14T10:00:00Z',
    albums: DEMO_ALBUMS[0],
  },
  {
    id: 'post-2',
    album_id: 'album-2',
    caption: 'Beach sunset walk 🌅 Nothing beats this view with you.',
    media_url: '/demo/couple2.svg',
    media_type: 'image',
    thumbnail_url: null,
    date_taken: '2024-03-20',
    is_featured: true,
    created_at: '2024-03-20T17:00:00Z',
    albums: DEMO_ALBUMS[1],
  },
  {
    id: 'post-3',
    album_id: 'album-3',
    caption: 'Coffee date mornings ☕ My favorite way to start the day.',
    media_url: '/demo/couple3.svg',
    media_type: 'image',
    thumbnail_url: null,
    date_taken: '2024-04-10',
    is_featured: true,
    created_at: '2024-04-10T08:00:00Z',
    albums: DEMO_ALBUMS[2],
  },
  {
    id: 'post-4',
    album_id: 'album-1',
    caption: 'Dancing in the rain 🌧️ Because why not?',
    media_url: '/demo/couple4.svg',
    media_type: 'image',
    thumbnail_url: null,
    date_taken: '2024-05-01',
    is_featured: true,
    created_at: '2024-05-01T14:00:00Z',
    albums: DEMO_ALBUMS[0],
  },
  {
    id: 'post-5',
    album_id: 'album-2',
    caption: 'Mountain hiking trip 🏔️ We made it to the top together!',
    media_url: '/demo/couple5.svg',
    media_type: 'image',
    thumbnail_url: null,
    date_taken: '2024-06-15',
    is_featured: false,
    created_at: '2024-06-15T11:00:00Z',
    albums: DEMO_ALBUMS[1],
  },
  {
    id: 'post-6',
    album_id: 'album-3',
    caption: 'Cooking together 🍳 Our secret recipe.',
    media_url: '/demo/couple6.svg',
    media_type: 'image',
    thumbnail_url: null,
    date_taken: '2024-07-20',
    is_featured: false,
    created_at: '2024-07-20T19:00:00Z',
    albums: DEMO_ALBUMS[2],
  },
];

export function getDemoStats() {
  return {
    totalPosts: DEMO_POSTS.length,
    totalAlbums: DEMO_ALBUMS.length,
    totalFeatured: DEMO_POSTS.filter(p => p.is_featured).length,
  };
}
